# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gimage < Formula
  desc "AI-powered image generation and processing CLI"
  homepage "https://github.com/chadneal/gimage"
  version "1.1.12"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chadneal/gimage/releases/download/v1.1.12/gimage_1.1.12_Darwin_x86_64.tar.gz"
      sha256 "2c32d49ab735e29041cd389ce9df106f283dd12342de12fbb5ffefa2dd9cf369"

      def install
        bin.install "gimage"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/chadneal/gimage/releases/download/v1.1.12/gimage_1.1.12_Darwin_arm64.tar.gz"
      sha256 "42c908641a3680a2acfc091e740fc85f5e2e57f333ef5e4571161a606a094ba6"

      def install
        bin.install "gimage"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/chadneal/gimage/releases/download/v1.1.12/gimage_1.1.12_Linux_x86_64.tar.gz"
      sha256 "8c5a663dd4e35a84954ac50601615005bc7d56a46facbb3682d0e44d8341e750"
      def install
        bin.install "gimage"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chadneal/gimage/releases/download/v1.1.12/gimage_1.1.12_Linux_arm64.tar.gz"
      sha256 "276f4f977a7c2c67f5ed33d3f8195ca27e0edc89146719005d6f46f40cc4994d"
      def install
        bin.install "gimage"
      end
    end
  end

  def caveats
    <<~EOS
      To get started with gimage:

      1. Set up API credentials:
         gimage auth gemini

      2. Get your free Gemini API key:
         https://aistudio.google.com/app/apikey

      3. Generate your first image:
         gimage generate "a sunset over mountains"

      For full documentation:
      https://github.com/chadneal/gimage
    EOS
  end

  test do
    system "#{bin}/gimage", "--version"
  end
end
