# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gimage < Formula
  desc "AI-powered image generation and processing CLI"
  homepage "https://github.com/chadneal/gimage"
  version "1.1.14"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chadneal/gimage/releases/download/v1.1.14/gimage_1.1.14_Darwin_x86_64.tar.gz"
      sha256 "7f1e7a2de57b505a6223bd5249c0ab4f3f165a5fa2858a200e995bde3c9b7647"

      def install
        bin.install "gimage"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/chadneal/gimage/releases/download/v1.1.14/gimage_1.1.14_Darwin_arm64.tar.gz"
      sha256 "23d768b22f68f412e8d4947770d6f240b6d8342cf6bdc2d690151b43c48781f8"

      def install
        bin.install "gimage"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/chadneal/gimage/releases/download/v1.1.14/gimage_1.1.14_Linux_x86_64.tar.gz"
      sha256 "371e8ec8e5a5d7abd46734b3f5ffd4350d15998bb540d775a146a4fe6128cfa8"
      def install
        bin.install "gimage"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chadneal/gimage/releases/download/v1.1.14/gimage_1.1.14_Linux_arm64.tar.gz"
      sha256 "e377def3f1cd361194a2f51084d9b3bab7a5536991142852f97614ce101b3dca"
      def install
        bin.install "gimage"
      end
    end
  end

  def caveats
    <<~EOS
      To get started with gimage:

      1. Set up API credentials:
         gimage auth gemini

      2. Get your free Gemini API key:
         https://aistudio.google.com/app/apikey

      3. Generate your first image:
         gimage generate "a sunset over mountains"

      For full documentation:
      https://github.com/chadneal/gimage
    EOS
  end

  test do
    system "#{bin}/gimage", "--version"
  end
end
